# Generated by Django 4.0 on 2022-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('content', models.TextField(blank=True, verbose_name='Текст записи')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Родителям',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Главная'},
        ),
    ]
